feat(fed): Searching content improved

diff --git a/bin/fed b/bin/fed
--- a/bin/fed
+++ b/bin/fed
@@ -81,11 +81,18 @@ fi
 files_cmd="fds --color=always -L -tf '$pattern'"
 
 # Set grep command
+# if command -v 'rg' &>/dev/null; then
+#   grep_all_cmd="rg --with-filename --line-number --color=always $FED_RG_ARGS {q}"
+# else
+#   # grep -h -n --color=always -R
+#   grep_all_cmd="grep --with-filename --line-number --color=always --dereference-recursive $FED_RG_ARGS {q}"
+# fi
+
 if command -v 'rg' &>/dev/null; then
-  grep_cmd="rg --with-filename --line-number --color=always $FED_RG_ARGS {q}"
+  grep_cmd="rg --files-with-matches --color=always $FED_RG_ARGS {q} || true"
 else
   # grep -h -n --color=always -R
-  grep_cmd="grep --with-filename --line-number --color=always --dereference-recursive $FED_RG_ARGS {q}"
+  grep_cmd="grep --files-with-matches --color=always --dereference-recursive $FED_RG_ARGS {q} || true"
 fi
 
 # Preview window command
@@ -103,6 +110,20 @@ preview_cmd="
       --highlight-line=\$NUMBER -- \"\$FILE\"
   else
     cat -- \"\$FILE\"
+  fi
+"
+
+if command -v 'delta' &>/dev/null; then
+  preview_grep='rg --pretty --context 5 --json {q} {} | delta'
+else
+  preview_grep='rg --pretty --context 5 {q} {}'
+fi
+
+preview_grep="
+  if [ -f {} ]; then
+    $preview_grep
+  else
+    echo 'Not found'
   fi
 "
 
@@ -126,12 +147,12 @@ done < <(fzf \
     --bind 'alt-up:preview-page-up,alt-down:preview-page-down' \
     --bind 'ctrl-^:toggle-preview' \
     --bind 'ctrl-s:toggle-sort' \
-    --bind 'ctrl-f:unbind(change,ctrl-f)+change-prompt(Select> )+enable-search+clear-query+rebind(ctrl-r,alt-r)' \
+    --bind "ctrl-f:unbind(change,ctrl-f)+change-prompt(Narrow> )+enable-search+clear-query+rebind(ctrl-r)+change-preview:$preview_cmd" \
     --bind 'shift-up:preview-up,shift-down:preview-down' \
     --bind "start:unbind(change)+reload($files_cmd)" \
-    --bind "alt-r:reload($files_cmd)" \
+    --bind "alt-r:unbind(change,ctrl-f)+change-prompt(Select> )+enable-search+reload($files_cmd)+rebind(ctrl-r)+change-preview:$preview_cmd" \
     --bind "change:reload:$grep_cmd" \
-    --bind "ctrl-r:unbind(ctrl-r,alt-r)+change-prompt(Search> )+disable-search+reload($grep_cmd)+rebind(change,ctrl-f)" \
+    --bind "ctrl-r:unbind(ctrl-r)+change-prompt(Search> )+disable-search+reload($grep_cmd)+rebind(change,ctrl-f)+change-preview:$preview_grep" \
     --delimiter : \
     --header "Search in: $location" \
     --history="$history_file" \
